### ISSUE TITLE
lssues

### ISSUE THREAD

**Issue by liuwenxin110012** [laonafahaodange/RepRFN#1]
你好，我遇到了一个问题，我在运行您的项目代码时，一个epoch要25分钟，我感觉有点不合理，batch-size我也设置为64。我训练集也进行了裁剪使之分辨率更小。请问您知道这大概是什么原因吗？

**Comment by laonafahaodange** [comment]
> 你好，我遇到了一个问题，我在运行您的项目代码时，一个epoch要25分钟，我感觉有点不合理，batch-size我也设置为64。我训练集也进行了裁剪使之分辨率更小。请问您知道这大概是什么原因吗？

你好，关于这个问题，可能和以下几个方面有关：
1. 硬件，例如gpu，cpu，io等
2. 在dataloader中涉及到在cpu上对图像进行预处理再将数据转移到gpu，这部分相比于EDSR对数据集处理可能不是十分高效，导致了额外的时间开销
3. 数据规模
4. 网络模型涉及到多分支

以我自己为例，在项目代码框架的参数下，裁剪DIV2K+Flickr2K数据集为256x256，AutoDL平台单卡3090显卡运行x4 1000epoch需要大概一周，x2需要一个月，4090约可以缩短一半。

**Comment by weikangqi** [comment]
感谢优秀的工作，是否 有只用DIV2K训练的模型呢？

**Comment by laonafahaodange** [comment]
您好，仓库提供的模型文件由DF2K数据集（DIV2K+FLICKR2K）训练得到，没有只用DIV2K训练的模型，可以通过仓库代码配置数据集使其只使用DIV2K数据集进行训练。希望能帮助到您。&nbsp;


早睡早起
***@***.***



&nbsp;




------------------&nbsp;原始邮件&nbsp;------------------
发件人: ***@***.***&gt;; 
发送时间: 2024年8月17日(星期六) 晚上11:34
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; "State ***@***.***&gt;; 
主题: Re: [laonafahaodange/RepRFN] lssues (Issue #1)














 
感谢优秀的工作，是否 有只用DIV2K训练的模型呢？
