### ISSUE TITLE
FLOPs的计算

### ISSUE THREAD

**Issue by ChamingHong** [laonafahaodange/RepRFN#2]
您好，刚入门SR想问问 Table 1 中的FLOPs是推理5个数据集里的所有图片总共花费的计算量吗，但我运行您的 RepRFN.py 时，好像就一张（3， 256， 256）的图片就用了 25.2303G，所以感觉我的理解好像有问题，希望可以得到您的解答，谢谢

**Comment by laonafahaodange** [comment]
> 您好，刚入门SR想问问 Table 1 中的FLOPs是推理5个数据集里的所有图片总共花费的计算量吗，但我运行您的 RepRFN.py 时，好像就一张（3， 256， 256）的图片就用了 25.2303G，所以感觉我的理解好像有问题，希望可以得到您的解答，谢谢

您好，代码可以参考https://github.com/ofsoundof/NTIRE2023_ESR/blob/main/test_demo.py
第236行，在代码中FLOPs的计算是以输入1次256x256x3的数据为标准，而非5个数据集里所有图像。另外Table 1中使用的模型结构与最终使用的模型结构不同，所以FLOPs会有一定的区别。

**Comment by ChamingHong** [comment]
> > 您好，刚入门SR想问问 Table 1 中的FLOPs是推理5个数据集里的所有图片总共花费的计算量吗，但我运行您的 RepRFN.py 时，好像就一张（3， 256， 256）的图片就用了 25.2303G，所以感觉我的理解好像有问题，希望可以得到您的解答，谢谢
> 
> 您好，代码可以参考https://github.com/ofsoundof/NTIRE2023_ESR/blob/main/test_demo.py 第236行，在代码中FLOPs的计算是以输入1次256x256x3的数据为标准，而非5个数据集里所有图像。另外Table 1中使用的模型结构与最终使用的模型结构不同，所以FLOPs会有一定的区别。

非常感谢😸 ，所以说对于不同尺度的超分x2,x3,x8，在计算FLOPs时输入都是1次256x256x3数据吗？当我改变超分尺度，输入都是1次256x256x3数据时，所计算出的FLOPs都是二十多G，没有像Table 1中那样x2有85G，x3有38G，x4有22G，您知道这是为什么吗

**Comment by laonafahaodange** [comment]
> > > 您好，刚入门SR想问问 Table 1 中的FLOPs是推理5个数据集里的所有图片总共花费的计算量吗，但我运行您的 RepRFN.py 时，好像就一张（3， 256， 256）的图片就用了 25.2303G，所以感觉我的理解好像有问题，希望可以得到您的解答，谢谢
> > 
> > 
> > 您好，代码可以参考https://github.com/ofsoundof/NTIRE2023_ESR/blob/main/test_demo.py 第236行，在代码中FLOPs的计算是以输入1次256x256x3的数据为标准，而非5个数据集里所有图像。另外Table 1中使用的模型结构与最终使用的模型结构不同，所以FLOPs会有一定的区别。
> 
> 非常感谢😸 ，所以说对于不同尺度的超分x2,x3,x8，在计算FLOPs时输入都是1次256x256x3数据吗？当我改变超分尺度，输入都是1次256x256x3数据时，所计算出的FLOPs都是二十多G，没有像Table 1中那样x2有85G，x3有38G，x4有22G，您知道这是为什么吗

x2/3/8指的应该是Table2？Table2中为了与之前的算法进行比较，采用的方式是固定输出为720p的图像，也就是1280x720，再逆推输入尺寸。比如x2的输入就是640x360，而非256x256，具体可以参考论文中`In terms of model complexity, assuming that the model output is a 720P image`

**Comment by ChamingHong** [comment]
> > > > 您好，刚入门SR想问问 Table 1 中的FLOPs是推理5个数据集里的所有图片总共花费的计算量吗，但我运行您的 RepRFN.py 时，好像就一张（3， 256， 256）的图片就用了 25.2303G，所以感觉我的理解好像有问题，希望可以得到您的解答，谢谢
> > > 
> > > 
> > > 您好，代码可以参考https://github.com/ofsoundof/NTIRE2023_ESR/blob/main/test_demo.py 第236行，在代码中FLOPs的计算是以输入1次256x256x3的数据为标准，而非5个数据集里所有图像。另外Table 1中使用的模型结构与最终使用的模型结构不同，所以FLOPs会有一定的区别。
> > 
> > 
> > 非常感谢😸 ，所以说对于不同尺度的超分x2,x3,x8，在计算FLOPs时输入都是1次256x256x3数据吗？当我改变超分尺度，输入都是1次256x256x3数据时，所计算出的FLOPs都是二十多G，没有像Table 1中那样x2有85G，x3有38G，x4有22G，您知道这是为什么吗
> 
> x2/3/8指的应该是Table2？Table2中为了与之前的算法进行比较，采用的方式是固定输出为720p的图像，也就是1280x720，再逆推输入尺寸。比如x2的输入就是640x360，而非256x256，具体可以参考论文中`In terms of model complexity, assuming that the model output is a 720P image`

噢噢噢理解了理解了，万分感谢您！！！
