### ISSUE TITLE
使用DIV2K进行训练时遇到的问题

### ISSUE THREAD

**Issue by jiningapp** [laonafahaodange/RepRFN#4]
尊敬的作者您好，在尝试运行您的训练代码时，训练集使用了DIV2K的X4作为LR输入，开启了数据增强，batchsize按默认的64，会报错如下：RuntimeError: stack expects each tensor to be equal size, but got [3, 510, 339] at entry 0 and [3, 291, 510] at entry 2

但是batchsize设置为1的时候可以正常进行训练。请问一下，这个是什么原因呢？是因为训练数据集需要提前预处理成一样的大小吗，还是说我的训练集的LR和HR图片没有完全1V1对应上，或者是别的可能的原因？

**Comment by jiningapp** [comment]
或者说，训练的时候batchsize只能设置为1吗

**Comment by laonafahaodange** [comment]
> 或者说，训练的时候batchsize只能设置为1吗

您好，batchsize可以设置为任意，鉴于您所描述的情况，推测应该是LR和HR图片未完全对应上，可以先检查一下LR和HR的图像数量以及尺寸、通道数关系？

**Comment by jiningapp** [comment]
DIV2K数据集是从官网下载的：https://data.vision.ee.ethz.ch/cvl/DIV2K/
下载后按官网建议的目录格式安放，然后实验配置如下：
```
# Data specifications
    parser.add_argument("--train_hr_dir", default=r"E:\dataset\DIV2K\DIV2K_train_HR", type=str,
                        help="Train Dataset GT Image Directory")
    parser.add_argument("--train_lr_dir", default=r"E:\dataset\DIV2K\DIV2K_train_LR_bicubic\X4", type=str,
                        help="Train Dataset LR Image Directory")
    parser.add_argument("--valid_hr_dir", default=r"E:\dataset\DIV2K\DIV2K_valid_HR", type=str,
                        help="Valid Dataset GT Image Directory")
    parser.add_argument("--valid_lr_dir", default=r"E:\dataset\DIV2K\DIV2K_valid_LR_bicubic\X4", type=str,
                        help="Valid Dataset LR Image Directory")
    parser.add_argument("--test_hr_dir", default=r"E:\dataset\Set14\image_HR", type=str,
                        help="Test Dataset GT Image Directory")
    parser.add_argument("--test_lr_dir", default=r"E:\dataset\Set14\LRbicx4", type=str,
                        help="Test Dataset LR Image Directory")
    parser.add_argument("--augment", default=True, action="store_true",
                        help="Data Augmentation, Includes hflip/vflip/rot90")
```

今天重新下载了官网数据集，还是重复报错：
```
RuntimeError: stack expects each tensor to be equal size, but got [3, 339, 510] at entry 0 and [3, 261, 510] at entry 2
```

**Comment by jiningapp** [comment]
作者您好，阅读了您前面已经close的issue发现，您的训练数据集是经过裁剪的256×256的图片（这样任意batchsize就不会报错），请问一下这个256×256是对官方训练集的LR进行裁剪的吗，能否提供一下这个训练数据集的处理代码，或者处理好的训练集，或者告诉一下裁剪策略是什么，因为希望可以复现一下效果，想要尽量使用一致的训练集，非常感谢您可以抽出时间回复我！

**Comment by laonafahaodange** [comment]
> 作者您好，阅读了您前面已经close的issue发现，您的训练数据集是经过裁剪的256×256的图片（这样任意batchsize就不会报错），请问一下这个256×256是对官方训练集的LR进行裁剪的吗，能否提供一下这个训练数据集的处理代码，或者处理好的训练集，或者告诉一下裁剪策略是什么，因为希望可以复现一下效果，想要尽量使用一致的训练集，非常感谢您可以抽出时间回复我！

这个256x256是对官方HR进行裁剪的（当时自己用python写了个裁剪，然后用matlab进行下采样好像是，但是裁剪的代码已经找不到了，下采样的代码倒是还有）。具体逻辑是设置裁剪的大小和移动步长对HR进行裁剪，不满足裁剪大小的部分就舍弃掉。得到裁剪的HR图像后，再对HR图像进行下采样得到LR。
裁剪的数据集比较大，不是很方便上传。推荐一个主流的超分辨率框架BasicSR，关于裁剪部分的代码可以参考
[https://github.com/XPixelGroup/BasicSR/blob/master/scripts/data_preparation/extract_subimages.py](https://github.com/XPixelGroup/BasicSR/blob/master/scripts/data_preparation/extract_subimages.py)

**Comment by jiningapp** [comment]
非常感谢您的解答！前一两天试了下对HR图像进行480×480大小的裁剪，步长设置200像素，确实得到的HR训练集非常大，然后参考了一个框架：bicubic_pytorch进行下采样得到LR图，之后训练代码可以正常启动了，非常感谢您的开源，已经给您的项目加了star，未来的论文中也会引用您的文章！

**Comment by laonafahaodange** [comment]
> 非常感谢您的解答！前一两天试了下对HR图像进行480×480大小的裁剪，步长设置200像素，确实得到的HR训练集非常大，然后参考了一个框架：bicubic_pytorch进行下采样得到LR图，之后训练代码可以正常启动了，非常感谢您的开源，已经给您的项目加了star，未来的论文中也会引用您的文章！

很高兴能帮到您，祝工作顺利~
